# Generated by Django 5.2.4 on 2025-08-01 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.URLField(help_text='URL del producto analizado', max_length=500)),
                ('target_audience', models.TextField(help_text='Descripcion del publico objetivo')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('blog', 'Blog')], help_text='Plataforma de marketing seleccionada', max_length=50)),
                ('product_title', models.CharField(blank=True, max_length=300)),
                ('product_description', models.TextField(blank=True)),
                ('product_price', models.CharField(blank=True, max_length=50)),
                ('ai_response', models.TextField(blank=True, help_text='Respuesta generada por la IA')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=False, help_text='Si el analisis fue exitoso')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si fallo')),
            ],
            options={
                'verbose_name': 'Historial de Analisis',
                'verbose_name_plural': 'Historiales de Analisis',
                'ordering': ['-created_at'],
            },
        ),
    ]
