# Generated by Django 5.2.4 on 2025-08-01 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_url', models.URLField()),
                ('competitor_name', models.CharField(max_length=200)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('strategies', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('template_content', models.JSONField()),
                ('success_rate', models.FloatField(default=0.0)),
                ('times_used', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-success_rate', '-times_used'],
            },
        ),
        migrations.AlterModelOptions(
            name='analysishistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='competitor_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='conversion_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='estimated_budget',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='product_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='product_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='product_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='strategy_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='was_implemented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='ai_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('blog', 'Blog'), ('email', 'Email Marketing'), ('twitter', 'Twitter/X')], max_length=50),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='product_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='target_audience',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='analysishistory',
            index=models.Index(fields=['user', '-created_at'], name='analyzer_an_user_id_639ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='analysishistory',
            index=models.Index(fields=['platform', 'created_at'], name='analyzer_an_platfor_7458d3_idx'),
        ),
        migrations.AddField(
            model_name='competitoranalysis',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.analysishistory'),
        ),
    ]
