# Generated by Django 5.2.4 on 2025-08-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_add_reset_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_reset_date',
        ),
    ]
