# Generated by Django 5.2.4 on 2025-08-07 18:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_competitoranalysis_marketingtemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('plan', models.CharField(choices=[('free', 'Plan Gratuito'), ('pro', 'Plan Profesional'), ('premium', 'Plan Premium')], default='free', max_length=20)),
                ('plan_expires', models.DateTimeField(blank=True, null=True)),
                ('analyses_limit_monthly', models.IntegerField(default=5)),
                ('competitive_analyses_allowed', models.BooleanField(default=False)),
                ('pdf_exports_allowed', models.BooleanField(default=True)),
                ('templates_access', models.BooleanField(default=True)),
                ('api_access', models.BooleanField(default=False)),
                ('analyses_this_month', models.IntegerField(default=0)),
                ('total_analyses', models.IntegerField(default=0)),
                ('last_analysis', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('preferred_platform', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='competitoranalysis',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='analysishistory',
            name='analyzer_an_user_id_639ec8_idx',
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='additional_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='analysis_type',
            field=models.CharField(choices=[('basic', 'Análisis Básico'), ('competitive', 'Análisis Competitivo')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='budget',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='campaign_goal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='tone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='competitoranalysis',
            name='competitor_price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='marketingtemplate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competitoranalysis',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='analyzer.analysishistory'),
        ),
        migrations.AddIndex(
            model_name='analysishistory',
            index=models.Index(fields=['analysis_type', 'success'], name='analyzer_an_analysi_d583ee_idx'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_used', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
