# Generated by Django 5.2.4 on 2025-08-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_invitation_usagelog_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysishistory',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='analysishistory',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='analysishistory',
            name='product_rating',
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='budget',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='campaign_goal',
            field=models.CharField(default='conversions', max_length=50),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='platform',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='product_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='product_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='product_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='target_audience',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='tone',
            field=models.CharField(default='professional', max_length=20),
        ),
    ]
