# Generated by Django 5.2.4 on 2025-08-12 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_reset_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
