# Generated by Django 5.2.4

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_userprofile_last_reset_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUsageTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('requests_count', models.PositiveIntegerField(default=1)),
                ('last_request', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'date'], name='analyzer_an_ip_addr_5f7c23_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='anonymoususagetracker',
            unique_together={('ip_address', 'date')},
        ),
    ]